# Generated by Django 6.0.2 on 2026-02-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drink',
            table='drinks',
        ),
    ]
